id: P008117
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS94773
  title: རྨ་ལྷོ་རྫོང་གི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་ཡིག་༔་དེབ ༡.
  author: ''
  volumes:
    af28843e2d3948159d9be1577e235ca9:
      image_group_id: I00KG08133
      title: ''
      volume_number: 1
      total_pages: 149
ebook_metadata:
  title: རྨ་ལྷོ་རྫོང་གི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་ཡིག་༔་དེབ ༡.
  author: ''
  sku: P008117
  cover: cover.jpg
  layers:
  - pagination
