id: I66A5434C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:13:04+00:00'
last_modified: '2022-06-09T04:37:21.162151+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS94773
  title: རྨ་ལྷོ་རྫོང་གི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་ཡིག་༔་དེབ ༡.
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    10F5:
      image_group_id: I00KG08133
      title: 'Volume 1 of rma lho rdzong gi rig gnas lo rgyus dpyad yig : deb 1.'
      total_pages: 149
      order: 1
      base_file: 10F5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
